### PR TITLE
Updated to OpenVR SDK 1.11.11

### PR DESCRIPTION
**Pull request by Dazeilad**
- [x] Updated the openvr directory
- [x] Updated the WatchDogWakeUp class constructor to comply with the new SDK

### CODE REVIEW

**Comment by ParkerMc** [comment]
Thank you for making the pull request. Everything looks good in it. I would just need to test it. 

However, as I'm sure you've noticed this project is bearly started and hasn't been worked on in almost 3 years. If you like the idea of it and would like to work on it I'm happy to add you to the project and let you take over but it doesn't make sense to contribute to a dead project.

Again thank you for the pull request I honestly forgot about this project and I wish I had time to work on it.

**Comment by Dazeilad** [comment]
Hi, I'm glad you answered, as the project is old I didn't know if someone would answer :smile: 

Actually, I came across this project through another one : https://github.com/SimulaVR/Simula/issues/114
I'm trying to turn my smartphone into a 3D-screen. As I say in this ticket, I wasn't able to really test, so I'm not sure the driver is working. Maybe you can help me on this ? SteamVR didn't detect my phone...

I do not have a lot of programming skills, so I won't take over the project, but if it works like this, I think it may be enough.

**Comment by ParkerMc** [comment]
Gotcha. Unfortunately, it looks like we left off trying to get this driver working for the other person who was working on this project with me. This project as it stands right now only displays on the computer screen and in no way connects to the phone.

Like I said this project is barely started, and we only have the plans for it.

**Comment by alex9099** [comment]
Yeah, I am not sure why we left it, guess it was due to the lack of time (and I got a rift CV1, so... Yeah :/ )

As Parker said, I think we left it just making the driver recognisable by steamvr, but we didn't make any kind of connection to the phone. In theory it shouldnt be that difficult, *just* find some way to grab the computer screen and stream to phone (vnc as a bodged-ish solution) and do an app to stream IMU sensors from the phone to the computer.

I will hopefully have more time in a few weeks, so I will take a look at it

**Comment by ParkerMc** [comment]
I'd love to look into working on it more too. Alex, if you want to send me a message on gitter sometime, we can get on the same page.

As for this PR, I'll have to compile and test it later today.

**Comment by ParkerMc** [comment]
I'm going merge then look at the updates to the driver sample.

**Pull request merged**
